### ISSUE TITLE
Set up API Gateway lambda function as a Cloudflare Worker

### ISSUE THREAD

**Issue by gy-toxyc** [GY-CODING/gyweb#3]
The purpose of this issue is to set up a Cloudflare Worker (similar to AWS Lambda) that will serve us as our API Gateway with authentication.

# Tasks

- [x] Set it up on Cloudflare with minimal code.
- [x] Link it with a subdomain (`api.gycoding.com`).
- [x] Check if it works well.

In order for this issue to be closed, all tasks should be completed.
